name: Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login advaith-docker.winterfox.tech -u admin --password-stdin
      - name: Build
        run: docker build -t advaith-docker.winterfox.tech/yesno:${{github.sha}} .
      - name: Push
        run: docker push advaith-docker.winterfox.tech/yesno:${{github.sha}}
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
      - name: Set image
        run: kubectl set image deployment/yesno yesno=advaith-docker.winterfox.tech/yesno:${{github.sha}}
      - name: Rollout status
        run: kubectl rollout status deployment/yesno
